/**
 * Handler for generate_api_integration tool
 *
 * Invokes the LangGraph integration agent and formats the result
 * as a structured markdown guide for developers.
 */

import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { integrationArgumentsSchema } from "../tools/schemas.js";
import { createErrorResult, createSuccessResult, buildErrorMessage } from "../utils/results.js";
import { runIntegrationAgent } from "../lib/integrationAgent.js";
import { getActiveProvider } from "../lib/llmFactory.js";

// ---------------------------------------------------------------------------
// Response formatter
// ---------------------------------------------------------------------------

const INSTALL_COMMANDS: Record<string, (apiName: string) => string> = {
  typescript: (api) =>
    `npm install axios\n# or\nyarn add axios\n# Types included via @types/node`,
  javascript: (api) =>
    `npm install axios`,
  python: (api) =>
    `pip install httpx\n# or\npip install requests`,
  java: (api) =>
    `<!-- Maven -->\n<dependency>\n  <groupId>com.squareup.okhttp3</groupId>\n  <artifactId>okhttp</artifactId>\n  <version>4.12.0</version>\n</dependency>`,
  go: (api) =>
    `# Standard library only — no install needed\ngo mod tidy`,
  csharp: (api) =>
    `dotnet add package System.Net.Http`,
  php: (api) =>
    `composer require guzzlehttp/guzzle`,
  ruby: (api) =>
    `gem install httparty`,
};

function getInstallCommand(language: string, apiName: string): string {
  return (
    INSTALL_COMMANDS[language.toLowerCase()]?.(apiName) ??
    `# Install your preferred HTTP client for ${language}`
  );
}

function formatIntegrationGuide(result: {
  apiName: string;
  language: string;
  testFramework: string;
  code: string;
  tests: string;
}): string {
  const { apiName, language, testFramework, code, tests } = result;
  const langLabel = language.charAt(0).toUpperCase() + language.slice(1);
  const installCmd = getInstallCommand(language, apiName);
  const provider = getActiveProvider();

  const lines: string[] = [
    `# Integration Guide — \`${apiName}\` (${langLabel})`,
    "",
    `> Generated by LangGraph agent using **${provider}** model.`,
    `> Test framework: **${testFramework}**`,
    "",
    "---",
    "",
    "## 1. Prerequisites",
    "",
    "```bash",
    installCmd,
    "```",
    "",
    "---",
    "",
    `## 2. Integration Code (${langLabel})`,
    "",
    `\`\`\`${language}`,
    code.trim(),
    "```",
    "",
    "---",
    "",
    `## 3. Unit Tests (${testFramework})`,
    "",
    `\`\`\`${language}`,
    tests.trim(),
    "```",
    "",
    "---",
    "",
    "## 4. Next Steps",
    "",
    `- [ ] Set environment variables: \`API_BASE_URL\`, \`API_KEY\``,
    `- [ ] Run the tests: review mocks and adjust to your project structure`,
    `- [ ] For the full API spec: use \`get_apiary_blueprint("${apiName}")\``,
    `- [ ] For a quick overview: use \`get_apiary_blueprint_summary("${apiName}")\``,
  ];

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

export async function handleGenerateApiIntegration(
  rawArguments: unknown
): Promise<CallToolResult> {
  const parsedArgs = integrationArgumentsSchema.safeParse(rawArguments ?? {});
  if (!parsedArgs.success) {
    return createErrorResult(`Invalid arguments: ${parsedArgs.error.message}`);
  }

  const { apiName, language, useCase, testFramework } = parsedArgs.data;

  try {
    const result = await runIntegrationAgent({
      apiName,
      language,
      useCase,
      testFramework,
    });

    const guide = formatIntegrationGuide(result);
    return createSuccessResult(guide);
  } catch (error) {
    const message = buildErrorMessage(
      error,
      `Failed to generate integration for "${apiName}"`
    );
    return createErrorResult(message);
  }
}
